# @format
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  test-ios:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          install: true
        env:
          MISE_HTTP_TIMEOUT: 300
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test iOS
        run: >
          xcodebuild test -scheme swiftui-theming -destination "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro" | xcbeautify

  test-watchos:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Test watchOS
        run: >
          xcodebuild test -scheme swiftui-theming -destination "platform=watchOS Simulator,OS=11.2,name=Apple Watch Ultra 2 (49mm)" | xcbeautify
  test-visionos:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          install: true
      - name: Test visionOS
        run: >
          xcodebuild test -scheme swiftui-theming -destination "platform=visionOS Simulator,OS=2.2,name=Apple Vision Pro" | xcbeautify
  test-tvos:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Test tvOS
        run: >
          xcodebuild test -scheme swiftui-theming -destination "platform=tvOS Simulator,OS=18.2,name=Apple TV" | xcbeautify
  test-macos:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Test macOS
        run: >
          xcodebuild test -scheme swiftui-theming -destination "platform=macOS" | xcbeautify
